import { subject } from "./Subjects";
import { year } from "./Year";

export const questions = [
  //ALGEBRA LINEAR #000000

  //2016 #FF0000
  {
    // question: require("../assets/2016/AlgebraLinear/AlgLin01/AlgLin.png"),
    question: require("../../assets/2016/AlgebraLinear/AlgLin01/AlgLin.png"),
    answers: [
      require("../../assets/2016/AlgebraLinear/AlgLin01/Alt.a.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin01/Alt.b.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin01/Alt.c.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin01/Alt.d.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin01/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2016/AlgebraLinear/AlgLin01/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._16,
  },
  {
    question: require("../../assets/2016/AlgebraLinear/AlgLin02/AlgLin.png"),
    answers: [
      require("../../assets/2016/AlgebraLinear/AlgLin02/Alt.a(Correta).png"),
      require("../../assets/2016/AlgebraLinear/AlgLin02/Alt.b.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin02/Alt.c.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin02/Alt.d.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin02/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2016/AlgebraLinear/AlgLin02/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._16,
  },
  {
    question: require("../../assets/2016/AlgebraLinear/AlgLin03/AlgLin.png"),
    answers: [
      require("../../assets/2016/AlgebraLinear/AlgLin03/Alt.a.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin03/Alt.b.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin03/Alt.c.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin03/Alt.d.png"),
      require("../../assets/2016/AlgebraLinear/AlgLin03/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2016/AlgebraLinear/AlgLin03/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._16,
  },
  //2017 #00FF00
  {
    question: require("../../assets/2017/AlgebraLinear/AlgLin01/AlgLin.png"),
    answers: [
      require("../../assets/2017/AlgebraLinear/AlgLin01/Alt.a.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin01/Alt.b(Correta).png"),
      require("../../assets/2017/AlgebraLinear/AlgLin01/Alt.c.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin01/Alt.d.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin01/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2017/AlgebraLinear/AlgLin01/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._17,
  },
  {
    question: require("../../assets/2017/AlgebraLinear/AlgLin02/AlgLin.png"),
    answers: [
      require("../../assets/2017/AlgebraLinear/AlgLin02/Alt.a.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin02/Alt.b.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin02/Alt.c.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin02/Alt.d.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin02/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2017/AlgebraLinear/AlgLin02/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._17,
  },
  {
    question: require("../../assets/2017/AlgebraLinear/AlgLin03/AlgLin.png"),
    answers: [
      require("../../assets/2017/AlgebraLinear/AlgLin03/Alt.a.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin03/Alt.b(Correta).png"),
      require("../../assets/2017/AlgebraLinear/AlgLin03/Alt.c.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin03/Alt.d.png"),
      require("../../assets/2017/AlgebraLinear/AlgLin03/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2017/AlgebraLinear/AlgLin03/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._17,
  },
  //2018 #0000FF
  {
    question: require("../../assets/2018/AlgebraLinear/AlgLin01/AlgLin.png"),
    answers: [
      require("../../assets/2018/AlgebraLinear/AlgLin01/Alt.a.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin01/Alt.b.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin01/Alt.c.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin01/Alt.d(Correta).png"),
      require("../../assets/2018/AlgebraLinear/AlgLin01/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2018/AlgebraLinear/AlgLin01/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._18,
  },
  {
    question: require("../../assets/2018/AlgebraLinear/AlgLin02/AlgLin.png"),
    answers: [
      require("../../assets/2018/AlgebraLinear/AlgLin02/Alt.a(Correta).png"),
      require("../../assets/2018/AlgebraLinear/AlgLin02/Alt.b.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin02/Alt.c.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin02/Alt.d.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin02/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2018/AlgebraLinear/AlgLin02/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._18,
  },
  {
    question: require("../../assets/2018/AlgebraLinear/AlgLin03/AlgLin.png"),
    answers: [
      require("../../assets/2018/AlgebraLinear/AlgLin03/Alt.a.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin03/Alt.b.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin03/Alt.c(Correta).png"),
      require("../../assets/2018/AlgebraLinear/AlgLin03/Alt.d.png"),
      require("../../assets/2018/AlgebraLinear/AlgLin03/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2018/AlgebraLinear/AlgLin03/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._18,
  },
  //2019 #FFFFFF
  {
    question: require("../../assets/2019/AlgebraLinear/AlgLin01/AlgLin.png"),
    answers: [
      require("../../assets/2019/AlgebraLinear/AlgLin01/Alt.a(Correta).png"),
      require("../../assets/2019/AlgebraLinear/AlgLin01/Alt.b.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin01/Alt.c.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin01/Alt.d.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin01/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2019/AlgebraLinear/AlgLin01/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._19,
  },
  {
    question: require("../../assets/2019/AlgebraLinear/AlgLin02/AlgLin.png"),
    answers: [
      require("../../assets/2019/AlgebraLinear/AlgLin02/Alt.a.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin02/Alt.b(Correta).png"),
      require("../../assets/2019/AlgebraLinear/AlgLin02/Alt.c.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin02/Alt.d.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin02/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2019/AlgebraLinear/AlgLin02/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._19,
  },
  {
    question: require("../../assets/2019/AlgebraLinear/AlgLin03/AlgLin.png"),
    answers: [
      require("../../assets/2019/AlgebraLinear/AlgLin03/Alt.a.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin03/Alt.b.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin03/Alt.c.png"),
      require("../../assets/2019/AlgebraLinear/AlgLin03/Alt.d(Correta).png"),
      require("../../assets/2019/AlgebraLinear/AlgLin03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2019/AlgebraLinear/AlgLin03/AlgLin_Res.png"),
    subject: subject.ALG,
    year: year._19,
  },
  //ANÁLISE COMBINATÓRIA #000000

  //2016 #FF0000
  {
    question: require("../../assets/2016/AnaliseCombinatoria/AnComb01/AnComb.png"),
    answers: [
      require("../../assets/2016/AnaliseCombinatoria/AnComb01/Alt.a.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb01/Alt.b.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb01/Alt.c.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb01/Alt.d(Correta).png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb01/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2016/AnaliseCombinatoria/AnComb01/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._16,
  },
  {
    question: require("../../assets/2016/AnaliseCombinatoria/AnComb02/AnComb.png"),
    answers: [
      require("../../assets/2016/AnaliseCombinatoria/AnComb02/Alt.a.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb02/Alt.b.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb02/Alt.c.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb02/Alt.d.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb02/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2016/AnaliseCombinatoria/AnComb02/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._16,
  },
  {
    question: require("../../assets/2016/AnaliseCombinatoria/AnComb03/AnComb.png"),
    answers: [
      require("../../assets/2016/AnaliseCombinatoria/AnComb03/Alt.a.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb03/Alt.b(Correta).png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb03/Alt.c.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb03/Alt.d.png"),
      require("../../assets/2016/AnaliseCombinatoria/AnComb03/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2016/AnaliseCombinatoria/AnComb03/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._16,
  },
  //2017 #00FF00
  {
    question: require("../../assets/2017/AnaliseCombinatoria/AnComb01/AnComb.png"),
    answers: [
      require("../../assets/2017/AnaliseCombinatoria/AnComb01/Alt.a.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb01/Alt.b(Correta).png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb01/Alt.c.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb01/Alt.d.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb01/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2017/AnaliseCombinatoria/AnComb01/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._17,
  },
  {
    question: require("../../assets/2017/AnaliseCombinatoria/AnComb02/AnComb.png"),
    answers: [
      require("../../assets/2017/AnaliseCombinatoria/AnComb02/Alt.a.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb02/Alt.b.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb02/Alt.c(Correta).png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb02/Alt.d.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb02/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2017/AnaliseCombinatoria/AnComb02/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._17,
  },
  {
    question: require("../../assets/2017/AnaliseCombinatoria/AnComb03/AnComb.png"),
    answers: [
      require("../../assets/2017/AnaliseCombinatoria/AnComb03/Alt.a.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb03/Alt.b.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb03/Alt.c.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb03/Alt.d.png"),
      require("../../assets/2017/AnaliseCombinatoria/AnComb03/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2017/AnaliseCombinatoria/AnComb03/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._17,
  },
  //2018 #0000FF
  {
    question: require("../../assets/2018/AnaliseCombinatoria/AnComb01/AnComb.png"),
    answers: [
      require("../../assets/2018/AnaliseCombinatoria/AnComb01/Alt.a.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb01/Alt.b.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb01/Alt.c.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb01/Alt.d(Correta).png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb01/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2018/AnaliseCombinatoria/AnComb01/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._18,
  },
  {
    question: require("../../assets/2018/AnaliseCombinatoria/AnComb02/AnComb.png"),
    answers: [
      require("../../assets/2018/AnaliseCombinatoria/AnComb02/Alt.a.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb02/Alt.b.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb02/Alt.c.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb02/Alt.d(Correta).png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb02/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2018/AnaliseCombinatoria/AnComb02/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._18,
  },
  {
    question: require("../../assets/2018/AnaliseCombinatoria/AnComb03/AnComb.png"),
    answers: [
      require("../../assets/2018/AnaliseCombinatoria/AnComb03/Alt.a.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb03/Alt.b.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb03/Alt.c(Correta).png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb03/Alt.d.png"),
      require("../../assets/2018/AnaliseCombinatoria/AnComb03/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2018/AnaliseCombinatoria/AnComb03/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._18,
  },
  //2019 #FFFFFF
  {
    question: require("../../assets/2019/AnaliseCombinatoria/AnComb01/AnComb.png"),
    answers: [
      require("../../assets/2019/AnaliseCombinatoria/AnComb01/Alt.a.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb01/Alt.b.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb01/Alt.c(Correta).png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb01/Alt.d.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb01/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2019/AnaliseCombinatoria/AnComb01/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._19,
  },
  {
    question: require("../../assets/2019/AnaliseCombinatoria/AnComb02/AnComb.png"),
    answers: [
      require("../../assets/2019/AnaliseCombinatoria/AnComb02/Alt.a.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb02/Alt.b.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb02/Alt.c(Correta).png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb02/Alt.d.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb02/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2019/AnaliseCombinatoria/AnComb02/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._19,
  },
  {
    question: require("../../assets/2019/AnaliseCombinatoria/AnComb03/AnComb.png"),
    answers: [
      require("../../assets/2019/AnaliseCombinatoria/AnComb03/Alt.a.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb03/Alt.b.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb03/Alt.c.png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb03/Alt.d(Correta).png"),
      require("../../assets/2019/AnaliseCombinatoria/AnComb03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2019/AnaliseCombinatoria/AnComb03/AnComb_Res.png"),
    subject: subject.ANAL,
    year: year._19,
  },
  //CALCULO DIFERENCIAL #000000

  //2016 #FF0000
  {
    question: require("../../assets/2016/CalculoDiferencial/CalcDif01/CalcDif.png"),
    answers: [
      require("../../assets/2016/CalculoDiferencial/CalcDif01/Alt.a(Correta).png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif01/Alt.b.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif01/Alt.c.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif01/Alt.d.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif01/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2016/CalculoDiferencial/CalcDif01/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._16,
  },
  {
    question: require("../../assets/2016/CalculoDiferencial/CalcDif02/CalcDif.png"),
    answers: [
      require("../../assets/2016/CalculoDiferencial/CalcDif02/Alt.a(Correta).png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif02/Alt.b.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif02/Alt.c.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif02/Alt.d.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif02/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2016/CalculoDiferencial/CalcDif02/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._16,
  },
  {
    question: require("../../assets/2016/CalculoDiferencial/CalcDif03/CalcDif.png"),
    answers: [
      require("../../assets/2016/CalculoDiferencial/CalcDif03/Alt.a.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif03/Alt.b.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif03/Alt.c.png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif03/Alt.d(Correta).png"),
      require("../../assets/2016/CalculoDiferencial/CalcDif03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2016/CalculoDiferencial/CalcDif03/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._16,
  },
  //2017 #00FF00
  {
    question: require("../../assets/2017/CalculoDiferencial/CalcDif01/CalcDif.png"),
    answers: [
      require("../../assets/2017/CalculoDiferencial/CalcDif01/Alt.a(Correta).png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif01/Alt.b.png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif01/Alt.c.png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif01/Alt.d.png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif01/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2017/CalculoDiferencial/CalcDif01/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._17,
  },
  {
    question: require("../../assets/2017/CalculoDiferencial/CalcDif02/CalcDif.png"),
    answers: [
      require("../../assets/2017/CalculoDiferencial/CalcDif02/Alt.a.png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif02/Alt.b.png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif02/Alt.c.png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif02/Alt.d.png"),
      require("../../assets/2017/CalculoDiferencial/CalcDif02/Alt.e(Correta).png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2017/CalculoDiferencial/CalcDif02/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._17,
  },
  //2018 #0000FF
  {
    question: require("../../assets/2018/CalculoDiferencial/CalcDif01/CalcDif.png"),
    answers: [
      require("../../assets/2018/CalculoDiferencial/CalcDif01/Alt.a.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif01/Alt.b.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif01/Alt.c.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif01/Alt.d.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif01/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2018/CalculoDiferencial/CalcDif01/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._18,
  },
  {
    question: require("../../assets/2018/CalculoDiferencial/CalcDif02/CalcDif.png"),
    answers: [
      require("../../assets/2018/CalculoDiferencial/CalcDif02/Alt.a.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif02/Alt.b(Correta).png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif02/Alt.c.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif02/Alt.d.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif02/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2018/CalculoDiferencial/CalcDif02/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._18,
  },
  {
    question: require("../../assets/2018/CalculoDiferencial/CalcDif03/CalcDif.png"),
    answers: [
      require("../../assets/2018/CalculoDiferencial/CalcDif03/Alt.a.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif03/Alt.b(Correta).png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif03/Alt.c.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif03/Alt.d.png"),
      require("../../assets/2018/CalculoDiferencial/CalcDif03/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2018/CalculoDiferencial/CalcDif03/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._18,
  },
  //2019 #FFFFFF
  {
    question: require("../../assets/2019/CalculoDiferencial/CalcDif01/CalcDif.png"),
    answers: [
      require("../../assets/2019/CalculoDiferencial/CalcDif01/Alt.a.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif01/Alt.b.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif01/Alt.c.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif01/Alt.d.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif01/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2019/CalculoDiferencial/CalcDif01/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._19,
  },
  {
    question: require("../../assets/2019/CalculoDiferencial/CalcDif02/CalcDif.png"),
    answers: [
      require("../../assets/2019/CalculoDiferencial/CalcDif02/Alt.a.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif02/Alt.b(Correta).png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif02/Alt.c.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif02/Alt.d.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif02/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2019/CalculoDiferencial/CalcDif02/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._19,
  },
  {
    question: require("../../assets/2019/CalculoDiferencial/CalcDif03/CalcDif.png"),
    answers: [
      require("../../assets/2019/CalculoDiferencial/CalcDif03/Alt.a.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif03/Alt.b.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif03/Alt.c(Correta).png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif03/Alt.d.png"),
      require("../../assets/2019/CalculoDiferencial/CalcDif03/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2019/CalculoDiferencial/CalcDif03/CalcDif_Res.png"),
    subject: subject.CALC,
    year: year._19,
  },

  //GEOMETRIA ANALITICA #000000

  //2016 #FF0000
  {
    question: require("../../assets/2016/GeometriaAnalitica/GeoAn01/GeoAn.png"),
    answers: [
      require("../../assets/2016/GeometriaAnalitica/GeoAn01/Alt.a.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn01/Alt.b.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn01/Alt.c(Correta).png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn01/Alt.d.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn01/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2016/GeometriaAnalitica/GeoAn01/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._16,
  },
  {
    question: require("../../assets/2016/GeometriaAnalitica/GeoAn02/GeoAn.png"),
    answers: [
      require("../../assets/2016/GeometriaAnalitica/GeoAn02/Alt.a.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn02/Alt.b.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn02/Alt.c.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn02/Alt.d(Correta).png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn02/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2016/GeometriaAnalitica/GeoAn02/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._16,
  },
  {
    question: require("../../assets/2016/GeometriaAnalitica/GeoAn03/GeoAn.png"),
    answers: [
      require("../../assets/2016/GeometriaAnalitica/GeoAn03/Alt.a.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn03/Alt.b.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn03/Alt.c.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn03/Alt.d(Correta).png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2016/GeometriaAnalitica/GeoAn03/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._16,
  },
  {
    question: require("../../assets/2016/GeometriaAnalitica/GeoAn04/GeoAn.png"),
    answers: [
      require("../../assets/2016/GeometriaAnalitica/GeoAn04/Alt.a.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn04/Alt.b.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn04/Alt.c(Correta).png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn04/Alt.d.png"),
      require("../../assets/2016/GeometriaAnalitica/GeoAn04/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2016/GeometriaAnalitica/GeoAn04/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._16,
  },
  //2017 #00FF00
  {
    question: require("../../assets/2017/GeometriaAnalitica/GeoAn01/GeoAn.png"),
    answers: [
      require("../../assets/2017/GeometriaAnalitica/GeoAn01/Alt.a.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn01/Alt.b(Correta).png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn01/Alt.c.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn01/Alt.d.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn01/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2017/GeometriaAnalitica/GeoAn01/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._17,
  },
  {
    question: require("../../assets/2017/GeometriaAnalitica/GeoAn02/GeoAn.png"),
    answers: [
      require("../../assets/2017/GeometriaAnalitica/GeoAn02/Alt.a(Correta).png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn02/Alt.b.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn02/Alt.c.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn02/Alt.d.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn02/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2017/GeometriaAnalitica/GeoAn02/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._17,
  },
  {
    question: require("../../assets/2017/GeometriaAnalitica/GeoAn03/GeoAn.png"),
    answers: [
      require("../../assets/2017/GeometriaAnalitica/GeoAn03/Alt.a.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn03/Alt.b.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn03/Alt.c.png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn03/Alt.d(Correta).png"),
      require("../../assets/2017/GeometriaAnalitica/GeoAn03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2017/GeometriaAnalitica/GeoAn03/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._17,
  },
  //2018 #0000FF
  {
    question: require("../../assets/2018/GeometriaAnalitica/GeoAn01/GeoAn.png"),
    answers: [
      require("../../assets/2018/GeometriaAnalitica/GeoAn01/Alt.a.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn01/Alt.b(Correta).png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn01/Alt.c.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn01/Alt.d.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn01/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2018/GeometriaAnalitica/GeoAn01/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._18,
  },
  {
    question: require("../../assets/2018/GeometriaAnalitica/GeoAn02/GeoAn.png"),
    answers: [
      require("../../assets/2018/GeometriaAnalitica/GeoAn02/Alt.a.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn02/Alt.b.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn02/Alt.c.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn02/Alt.d.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn02/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2018/GeometriaAnalitica/GeoAn02/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._18,
  },
  {
    question: require("../../assets/2018/GeometriaAnalitica/GeoAn03/GeoAn.png"),
    answers: [
      require("../../assets/2018/GeometriaAnalitica/GeoAn03/Alt.a(Correta).png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn03/Alt.b.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn03/Alt.c.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn03/Alt.d.png"),
      require("../../assets/2018/GeometriaAnalitica/GeoAn03/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2018/GeometriaAnalitica/GeoAn03/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._18,
  },
  //2019 #FFFFFF
  {
    question: require("../../assets/2019/GeometriaAnalitica/GeoAn01/GeoAn.png"),
    answers: [
      require("../../assets/2019/GeometriaAnalitica/GeoAn01/Alt.a.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn01/Alt.b.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn01/Alt.c.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn01/Alt.d(Correta).png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn01/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2019/GeometriaAnalitica/GeoAn01/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._19,
  },
  {
    question: require("../../assets/2019/GeometriaAnalitica/GeoAn02/GeoAn.png"),
    answers: [
      require("../../assets/2019/GeometriaAnalitica/GeoAn02/Alt.a.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn02/Alt.b.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn02/Alt.c.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn02/Alt.d.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn02/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2019/GeometriaAnalitica/GeoAn02/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._19,
  },
  {
    question: require("../../assets/2019/GeometriaAnalitica/GeoAn03/GeoAn.png"),
    answers: [
      require("../../assets/2019/GeometriaAnalitica/GeoAn03/Alt.a(Correta).png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn03/Alt.b.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn03/Alt.c.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn03/Alt.d.png"),
      require("../../assets/2019/GeometriaAnalitica/GeoAn03/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2019/GeometriaAnalitica/GeoAn03/GeoAn_Res.png"),
    subject: subject.GEO,
    year: year._19,
  },

  //LÓGICA MATEMÁTICA #000000

  //2016 #FF0000
  {
    question: require("../../assets/2016/LogicaMatematica/LogMat01/LogMat.png"),
    answers: [
      require("../../assets/2016/LogicaMatematica/LogMat01/Alt.a(Correta).png"),
      require("../../assets/2016/LogicaMatematica/LogMat01/Alt.b.png"),
      require("../../assets/2016/LogicaMatematica/LogMat01/Alt.c.png"),
      require("../../assets/2016/LogicaMatematica/LogMat01/Alt.d.png"),
      require("../../assets/2016/LogicaMatematica/LogMat01/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2016/LogicaMatematica/LogMat01/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._16,
  },
  {
    question: require("../../assets/2016/LogicaMatematica/LogMat02/LogMat.png"),
    answers: [
      require("../../assets/2016/LogicaMatematica/LogMat02/Alt.a.png"),
      require("../../assets/2016/LogicaMatematica/LogMat02/Alt.b.png"),
      require("../../assets/2016/LogicaMatematica/LogMat02/Alt.c.png"),
      require("../../assets/2016/LogicaMatematica/LogMat02/Alt.d.png"),
      require("../../assets/2016/LogicaMatematica/LogMat02/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2016/LogicaMatematica/LogMat02/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._16,
  },
  {
    question: require("../../assets/2016/LogicaMatematica/LogMat03/LogMat.png"),
    answers: [
      require("../../assets/2016/LogicaMatematica/LogMat03/Alt.a.png"),
      require("../../assets/2016/LogicaMatematica/LogMat03/Alt.b.png"),
      require("../../assets/2016/LogicaMatematica/LogMat03/Alt.c.png"),
      require("../../assets/2016/LogicaMatematica/LogMat03/Alt.d(Correta).png"),
      require("../../assets/2016/LogicaMatematica/LogMat03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2016/LogicaMatematica/LogMat03/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._16,
  },
  //2017 #00FF00
  {
    question: require("../../assets/2017/LogicaMatematica/LogMat01/LogMat.png"),
    answers: [
      require("../../assets/2017/LogicaMatematica/LogMat01/Alt.a.png"),
      require("../../assets/2017/LogicaMatematica/LogMat01/Alt.b.png"),
      require("../../assets/2017/LogicaMatematica/LogMat01/Alt.c(Correta).png"),
      require("../../assets/2017/LogicaMatematica/LogMat01/Alt.d.png"),
      require("../../assets/2017/LogicaMatematica/LogMat01/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2017/LogicaMatematica/LogMat01/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._17,
  },
  {
    question: require("../../assets/2017/LogicaMatematica/LogMat02/LogMat.png"),
    answers: [
      require("../../assets/2017/LogicaMatematica/LogMat02/Alt.a(Correta).png"),
      require("../../assets/2017/LogicaMatematica/LogMat02/Alt.b.png"),
      require("../../assets/2017/LogicaMatematica/LogMat02/Alt.c.png"),
      require("../../assets/2017/LogicaMatematica/LogMat02/Alt.d.png"),
      require("../../assets/2017/LogicaMatematica/LogMat02/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2017/LogicaMatematica/LogMat02/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._17,
  },
  {
    question: require("../../assets/2017/LogicaMatematica/LogMat03/LogMat.png"),
    answers: [
      require("../../assets/2017/LogicaMatematica/LogMat03/Alt.a.png"),
      require("../../assets/2017/LogicaMatematica/LogMat03/Alt.b.png"),
      require("../../assets/2017/LogicaMatematica/LogMat03/Alt.c.png"),
      require("../../assets/2017/LogicaMatematica/LogMat03/Alt.d(Correta).png"),
      require("../../assets/2017/LogicaMatematica/LogMat03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2017/LogicaMatematica/LogMat03/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._17,
  },
  //2018 #0000FF
  {
    question: require("../../assets/2018/LogicaMatematica/LogMat01/LogMat.png"),
    answers: [
      require("../../assets/2018/LogicaMatematica/LogMat01/Alt.a.png"),
      require("../../assets/2018/LogicaMatematica/LogMat01/Alt.b(Correta).png"),
      require("../../assets/2018/LogicaMatematica/LogMat01/Alt.c.png"),
      require("../../assets/2018/LogicaMatematica/LogMat01/Alt.d.png"),
      require("../../assets/2018/LogicaMatematica/LogMat01/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2018/LogicaMatematica/LogMat01/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._18,
  },
  {
    question: require("../../assets/2018/LogicaMatematica/LogMat02/LogMat.png"),
    answers: [
      require("../../assets/2018/LogicaMatematica/LogMat02/Alt.a.png"),
      require("../../assets/2018/LogicaMatematica/LogMat02/Alt.b.png"),
      require("../../assets/2018/LogicaMatematica/LogMat02/Alt.c(Correta).png"),
      require("../../assets/2018/LogicaMatematica/LogMat02/Alt.d.png"),
      require("../../assets/2018/LogicaMatematica/LogMat02/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2018/LogicaMatematica/LogMat02/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._18,
  },
  {
    question: require("../../assets/2018/LogicaMatematica/LogMat03/LogMat.png"),
    answers: [
      require("../../assets/2018/LogicaMatematica/LogMat03/Alt.a.png"),
      require("../../assets/2018/LogicaMatematica/LogMat03/Alt.b.png"),
      require("../../assets/2018/LogicaMatematica/LogMat03/Alt.c(Correta).png"),
      require("../../assets/2018/LogicaMatematica/LogMat03/Alt.d.png"),
      require("../../assets/2018/LogicaMatematica/LogMat03/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2018/LogicaMatematica/LogMat03/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._18,
  },
  //2019 #FFFFFF
  {
    question: require("../../assets/2019/LogicaMatematica/LogMat01/LogMat.png"),
    answers: [
      require("../../assets/2019/LogicaMatematica/LogMat01/Alt.a.png"),
      require("../../assets/2019/LogicaMatematica/LogMat01/Alt.b.png"),
      require("../../assets/2019/LogicaMatematica/LogMat01/Alt.c(Correta).png"),
      require("../../assets/2019/LogicaMatematica/LogMat01/Alt.d.png"),
      require("../../assets/2019/LogicaMatematica/LogMat01/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2019/LogicaMatematica/LogMat01/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._19,
  },
  {
    question: require("../../assets/2019/LogicaMatematica/LogMat02/LogMat.png"),
    answers: [
      require("../../assets/2019/LogicaMatematica/LogMat02/Alt.a.png"),
      require("../../assets/2019/LogicaMatematica/LogMat02/Alt.b(Correta).png"),
      require("../../assets/2019/LogicaMatematica/LogMat02/Alt.c.png"),
      require("../../assets/2019/LogicaMatematica/LogMat02/Alt.d.png"),
      require("../../assets/2019/LogicaMatematica/LogMat02/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2019/LogicaMatematica/LogMat02/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._19,
  },
  {
    question: require("../../assets/2019/LogicaMatematica/LogMat03/LogMat.png"),
    answers: [
      require("../../assets/2019/LogicaMatematica/LogMat03/Alt.a.png"),
      require("../../assets/2019/LogicaMatematica/LogMat03/Alt.b(Correta).png"),
      require("../../assets/2019/LogicaMatematica/LogMat03/Alt.c.png"),
      require("../../assets/2019/LogicaMatematica/LogMat03/Alt.d.png"),
      require("../../assets/2019/LogicaMatematica/LogMat03/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2019/LogicaMatematica/LogMat03/LogMat_Res.png"),
    subject: subject.LOG,
    year: year._19,
  },

  //MATEMÁTICA DISCRETA #000000

  //2016 #FF0000
  {
    question: require("../../assets/2016/MatematicaDiscreta/MatDisc01/MatDisc.png"),
    answers: [
      require("../../assets/2016/MatematicaDiscreta/MatDisc01/Alt.a.png"),
      require("../../assets/2016/MatematicaDiscreta/MatDisc01/Alt.b.png"),
      require("../../assets/2016/MatematicaDiscreta/MatDisc01/Alt.c.png"),
      require("../../assets/2016/MatematicaDiscreta/MatDisc01/Alt.d(Correta).png"),
      require("../../assets/2016/MatematicaDiscreta/MatDisc01/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2016/MatematicaDiscreta/MatDisc01/MatDisc_Res.png"),
    subject: subject.MAT,
    year: year._16,
  },
  //2017 #00FF00
  //2018 #0000FF
  {
    question: require("../../assets/2018/MatematicaDiscreta/MatDisc01/MatDisc.png"),
    answers: [
      require("../../assets/2018/MatematicaDiscreta/MatDisc01/Alt.a.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc01/Alt.b(Correta).png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc01/Alt.c.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc01/Alt.d.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc01/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2018/MatematicaDiscreta/MatDisc01/MatDisc_Res.png"),
    subject: subject.MAT,
    year: year._18,
  },
  {
    question: require("../../assets/2018/MatematicaDiscreta/MatDisc02/MatDisc.png"),
    answers: [
      require("../../assets/2018/MatematicaDiscreta/MatDisc02/Alt.a.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc02/Alt.b.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc02/Alt.c(Correta).png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc02/Alt.d.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc02/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2018/MatematicaDiscreta/MatDisc02/MatDisc_Res.png"),
    subject: subject.MAT,
    year: year._18,
  },
  {
    question: require("../../assets/2018/MatematicaDiscreta/MatDisc03/MatDisc.png"),
    answers: [
      require("../../assets/2018/MatematicaDiscreta/MatDisc03/Alt.a.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc03/Alt.b.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc03/Alt.c.png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc03/Alt.d(Correta).png"),
      require("../../assets/2018/MatematicaDiscreta/MatDisc03/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2018/MatematicaDiscreta/MatDisc03/MatDisc_Res.png"),
    subject: subject.MAT,
    year: year._18,
  },
  //2019 #FFFFFF
  {
    question: require("../../assets/2019/MatematicaDiscreta/MatDisc01/MatDisc.png"),
    answers: [
      require("../../assets/2019/MatematicaDiscreta/MatDisc01/Alt.a(Correta).png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc01/Alt.b.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc01/Alt.c.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc01/Alt.d.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc01/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2019/MatematicaDiscreta/MatDisc01/MatDisc_Res.png"),
    subject: subject.MAT,
    year: year._19,
  },
  {
    question: require("../../assets/2019/MatematicaDiscreta/MatDisc02/MatDisc.png"),
    answers: [
      require("../../assets/2019/MatematicaDiscreta/MatDisc02/Alt.a.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc02/Alt.b.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc02/Alt.c.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc02/Alt.d.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc02/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2019/MatematicaDiscreta/MatDisc02/MatDisc_Res.png"),
    subject: subject.MAT,
    year: year._19,
  },
  {
    question: require("../../assets/2019/MatematicaDiscreta/MatDisc03/MatDisc.png"),
    answers: [
      require("../../assets/2019/MatematicaDiscreta/MatDisc03/Alt.a.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc03/Alt.b(Correta).png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc03/Alt.c.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc03/Alt.d.png"),
      require("../../assets/2019/MatematicaDiscreta/MatDisc03/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2019/MatematicaDiscreta/MatDisc03/MatDisc_Res.png"),
    subject: subject.MAT,
    year: year._19,
  },

  //PROBABILIDADE E ESTATISTICA #000000

  //2016 #FF0000
  {
    question: require("../../assets/2016/ProbabilidadeEstatistica/ProbEst01/ProbEst.png"),
    answers: [
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst01/Alt.a.png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst01/Alt.b.png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst01/Alt.c.png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst01/Alt.d.png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst01/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2016/ProbabilidadeEstatistica/ProbEst01/ProbEst_Res.png"),
    subject: subject.PBE,
    year: year._16,
  },
  {
    question: require("../../assets/2016/ProbabilidadeEstatistica/ProbEst02/ProbEst.png"),
    answers: [
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst02/Alt.a.png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst02/Alt.b(Correta).png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst02/Alt.c.png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst02/Alt.d.png"),
      require("../../assets/2016/ProbabilidadeEstatistica/ProbEst02/Alt.e.png"),
    ],
    correctAnswer: 2,
    explanation: require("../../assets/2016/ProbabilidadeEstatistica/ProbEst02/ProbEst_Res.png"),
    subject: subject.PBE,
    year: year._16,
  },
  //2017 #00FF00
  {
    question: require("../../assets/2017/ProbabilidadeEstatistica/ProbEst01/ProbEst.png"),
    answers: [
      require("../../assets/2017/ProbabilidadeEstatistica/ProbEst01/Alt.a.png"),
      require("../../assets/2017/ProbabilidadeEstatistica/ProbEst01/Alt.b.png"),
      require("../../assets/2017/ProbabilidadeEstatistica/ProbEst01/Alt.c(Correta).png"),
      require("../../assets/2017/ProbabilidadeEstatistica/ProbEst01/Alt.d.png"),
      require("../../assets/2017/ProbabilidadeEstatistica/ProbEst01/Alt.e.png"),
    ],
    correctAnswer: 3,
    explanation: require("../../assets/2017/ProbabilidadeEstatistica/ProbEst01/ProbEst_Res.png"),
    subject: subject.PBE,
    year: year._17,
  },
  //2018 #0000FF
  {
    question: require("../../assets/2018/ProbabilidadeEstatistica/ProbEst01/ProbEst.png"),
    answers: [
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst01/Alt.a.png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst01/Alt.b.png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst01/Alt.c.png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst01/Alt.d.png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst01/Alt.e(Correta).png"),
    ],
    correctAnswer: 5,
    explanation: require("../../assets/2018/ProbabilidadeEstatistica/ProbEst01/ProbEst_Res.png"),
    subject: subject.PBE,
    year: year._18,
  },
  {
    question: require("../../assets/2018/ProbabilidadeEstatistica/ProbEst02/ProbEst.png"),
    answers: [
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst02/Alt.a(Correta).png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst02/Alt.b.png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst02/Alt.c.png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst02/Alt.d.png"),
      require("../../assets/2018/ProbabilidadeEstatistica/ProbEst02/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2018/ProbabilidadeEstatistica/ProbEst02/ProbEst_Res.png"),
    subject: subject.PBE,
    year: year._18,
  },
  //2019 #FFFFFF
  {
    question: require("../../assets/2019/ProbabilidadeEstatistica/ProbEst01/ProbEst.png"),
    answers: [
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst01/Alt.a(Correta).png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst01/Alt.b.png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst01/Alt.c.png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst01/Alt.d.png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst01/Alt.e.png"),
    ],
    correctAnswer: 1,
    explanation: require("../../assets/2019/ProbabilidadeEstatistica/ProbEst01/ProbEst_Res.png"),
    subject: subject.PBE,
    year: year._19,
  },
  {
    question: require("../../assets/2019/ProbabilidadeEstatistica/ProbEst02/ProbEst.png"),
    answers: [
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst02/Alt.a.png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst02/Alt.b.png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst02/Alt.c.png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst02/Alt.d(Correta).png"),
      require("../../assets/2019/ProbabilidadeEstatistica/ProbEst02/Alt.e.png"),
    ],
    correctAnswer: 4,
    explanation: require("../../assets/2019/ProbabilidadeEstatistica/ProbEst02/ProbEst_Res.png"),
    subject: subject.PBE,
    year: year._19,
  },
];
